export const CognitiveTypes = {
  GOAL_LONG_TERM: "GOAL_LONG_TERM",
  GOAL_SHORT_TERM: "GOAL_SHORT_TERM",

  FRICTION_ACTIVE: "FRICTION_ACTIVE",
  FRICTION_RECURRING: "FRICTION_RECURRING",

  PREFERENCE_COMMUNICATION: "PREFERENCE_COMMUNICATION",
  PREFERENCE_ROUTINE: "PREFERENCE_ROUTINE",

  IDENTITY_CORE: "IDENTITY_CORE",
  VALUE_SYSTEM: "VALUE_SYSTEM",
} as const;

export type CognitiveType =
  (typeof CognitiveTypes)[keyof typeof CognitiveTypes];
